name: Deploy preview

on:
  pull_request_target: null

jobs:
  deploy:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Build
        run: |
          npm ci && \
          node ./scripts/set-homepage.cjs /shlink-web-client/${GITHUB_HEAD_REF#refs/heads/} && \
          node --run build
      - name: Deploy preview
        uses: shlinkio/deploy-preview-action@v1.0.1
        with:
          folder: build
